config/routes.rb
Rails.application.routes.draw do
  resources :benefices
  resources :tranches
  resources :repartitions
  resources :salaires
  resources :frais

  resources :associates
  resources :affaires

  resources :bilan, only: :index do
    collection do
      get :annuels
      get :mensuels
    end
  end

  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/affaire.rb
# == Schema Information
#
# Table name: affaires
#
#  id                    :bigint           not null, primary key
#  amount_cents          :integer          not null
#  label                 :string           not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  activite_mensuelle_id :bigint           not null
#  repartition_id        :bigint           not null
#
# Indexes
#
#  index_affaires_on_activite_mensuelle_id  (activite_mensuelle_id)
#  index_affaires_on_repartition_id         (repartition_id)
#
# Foreign Keys
#
#  fk_rails_...  (activite_mensuelle_id => activites_mensuelles.id)
#  fk_rails_...  (repartition_id => repartitions.id)
#

class Affaire < ApplicationRecord
  validates :amount, presence: true
  belongs_to :repartition
  belongs_to :activite_mensuelle, touch: true

  has_one :associate, through: :activite_mensuelle

  monetize :amount_cents, disable_validation: true

  def to_s
    label
  end
end

app/controllers/affaires_controller.rb
class AffairesController < ApplicationController
  def new
    @affaire = Affaire.new(activite_mensuelle: ActiviteMensuelle.find(params[:activite_mensuelle_id]))
    render partial: "form", locals: { affaire: @affaire }, layout: "layouts/app_modal_content"
   end

  def create
    params = affaire_params
    @affaire = Affaire.new(params)

    if @affaire.save
        flash.notice = 'Ajout du CA avec succès'
    else
        flash.alert = "Erreur à l’ajout du CA #{@affaire.errors.details}"
    end

    redirect_to @affaire.associate
  end

  def edit
    @affaire = Affaire.find(params[:id])
    render partial: "form", locals: { affaire: @affaire }, layout: "layouts/app_modal_content"
  end

  def update
    @affaire = Affaire.find(params[:id])

    if @affaire.update(affaire_params)
      flash.notice = 'CA modifié avec succès'
    else
      flash.alert = "Erreur à la modification du CA #{@affaire.errors.details}"
    end

    redirect_to @affaire.associate
  end

  def destroy
    @affaire = Affaire.find(params[:id])
    associate = @affaire.associate
    @affaire.destroy

    redirect_to associate
  end

  private

  def affaire_params
      params.require(:affaire).permit(:label, :amount, :repartition_id, :activite_mensuelle_id)
  end
end

app/views/affaires/_affaire.html.erb
<%= link_to edit_affaire_path(affaire), id: dom_id(affaire), class: "js-modal-trigger history-editable", data: { target: "app-modal", turbo_frame: "modal-content"} do %>
  <%= render 'value', label: affaire.label, note: affaire.repartition.label, amount: affaire.amount %>
<% end %>

app/views/affaires/_form.html.erb
<%= form_with model: affaire, data: { turbo_frame: "_top" } do |f| %>
  <%= f.hidden_field :activite_mensuelle_id %>

  <div class="field is-horizontal">
    <div class="field-label"></div>
    <div class="field-body">
      <div class="field">
        <h1 class="title"> <%= affaire.model_name.human %> </h1>
        <h2 class="subtitle"><%= affaire.activite_mensuelle.mois %></h2>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal"><%= f.label :label, class: "label" %></div>
    <div class="field-body">
      <div class="field">
        <div class="control"><%= f.text_field :label, class: "input" %></div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal"><%= f.label :amount, class: 'label' %></div>
    <div class="field-body">
      <div class="field">
        <div class="control"><%= f.money_field :amount, class: "input" %></div>
        <p class="help"><%= Affaire.human_attribute_name('notes.amount') %></p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal"><%= f.label :repartition, class: "label" %></div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <div class="select"><%= f.collection_select :repartition_id, Repartition.enabled, :id, :label, { }, class: "input" %></div>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label"></div>
    <div class="field-body">
      <div class="field is-grouped">
        <div class="control"><%= f.submit class: "button is-dark" %></div>
        <%= delete_button(affaire) %>
      </div>
    </div>
  </div>
<% end %>