config/routes.rb
Rails.application.routes.draw do
  resources :benefices
  resources :tranches
  resources :repartitions
  resources :salaires
  resources :frais

  resources :associates
  resources :affaires

  resources :bilan, only: :index do
    collection do
      get :annuels
      get :mensuels
    end
  end

  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/benefice.rb
# == Schema Information
#
# Table name: benefices
#
#  id           :bigint           not null, primary key
#  amount_cents :integer          not null
#  notes        :string
#  provisional  :boolean          not null
#  year         :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_benefices_on_year  (year) UNIQUE
#

class Benefice < ApplicationRecord
  validates :year, presence: true, uniqueness: true
  validates :amount, presence: true

  monetize :amount_cents, disable_validation: true
end

app/controllers/benefices_controller.rb
class BeneficesController < ApplicationController
  before_action :set_benefice, only: [:edit, :update, :destroy]

  def index
    @benefices = Benefice.all.order(:year)
  end

  def new
    @benefice = Benefice.new
  end

  def edit
  end

  def create
    @benefice = Benefice.new(benefice_params)

    if @benefice.save
      redirect_to benefices_url, notice: "Le bénéfice de l’année #{@benefice.year} a été ajouté."
    else
      render :new
    end
  end

  def update
    if @benefice.update(benefice_params)
      redirect_to benefices_url, notice: "Le bénéfice de l’année #{@benefice.year} a été mis à jour."
    else
      render :edit
    end
  end

  def destroy
    benefice_year = @benefice.year
    @benefice.destroy
    redirect_to benefices_url, notice: "Le bénéfice de l’année #{benefice_year} a été supprimé."
  end

  private

  def set_benefice
    @benefice = Benefice.find(params[:id])
  end

  def benefice_params
    params.require(:benefice).permit(:year, :amount, :provisional, :notes)
  end
end

app/helpers/benefices_helper.rb
module BeneficesHelper
end

app/views/benefices/_form.html.erb
<%= form_with(model: benefice, local: true) do |form| %>
  <% if benefice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(benefice.errors.count, "error") %> prohibited this benefice from being saved:</h2>

      <ul>
        <% benefice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :year, class: "label" %>
    </div>
    <div class="field-body">
      <%= form.number_field :year, disabled: benefice.persisted?, class: "input" %>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :amount, class: "label" %>
    </div>
    <div class="field-body">
      <%= form.money_field :amount, class: "input" %>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :provisional, class: "label" %>
    </div>
    <div class="field-body">
      <%= form.check_box :provisional %>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label">
      <%= form.label :notes, class: "label" %>
    </div>
    <div class="field-body">
      <%= form.text_field :notes, class: "input" %>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label">
    </div>
    <div class="field-body">
      <%= form.submit 'Enregistrer', class: "button is-primary" %>
    </div>
  </div>
<% end %>

app/views/benefices/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Modification du bénéfice <%= @benefice.year %></h1>
    <h2 class="subtitle">
      <%= link_to 'Supprimer', benefice_path,
            class: 'button is-danger is-outlined is-small',
            data: { confirm: "Supprimer le bénéfice de #{@benefice.year} ?", method: :delete} %>
    </h2>

    <%= render 'form', benefice: @benefice %>
    <br/>
  </div>
</section>

app/views/benefices/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Liste des bénéfices</h1>

    <table class="table is-bordered is-striped">
      <thead>
        <tr>
          <th><%= Benefice.human_attribute_name(:year) %></th>
          <th><%= Benefice.human_attribute_name(:amount) %></th>
          <th><%= Benefice.human_attribute_name(:notes) %></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @benefices.each do |benefice| %>
          <tr>
            <td><%= benefice.year %></td>
            <td>
              <%= benefice.amount.format %>
              <% if benefice.provisional? %>
                (<%= Benefice.human_attribute_name(:provisional).downcase %>)
              <% end %>
            </td>
            <td><%= benefice.notes %></td>
            <td><%= link_to 'Modifier', edit_benefice_path(benefice) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Ajouter le bénéfice d’une année', new_benefice_path,  class: "button is-primary" %>
  </div>
</section>

app/views/benefices/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Nouveau bénéfice</h1>

    <%= render 'form', benefice: @benefice %>
    <br/>

    <%= link_to 'Retour', benefices_path, class: "button is-text" %>
  </div>
</section>