config/routes.rb
Rails.application.routes.draw do
  resources :benefices
  resources :tranches
  resources :repartitions
  resources :salaires
  resources :frais

  resources :associates
  resources :affaires

  resources :bilan, only: :index do
    collection do
      get :annuels
      get :mensuels
    end
  end

  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/repartition.rb
# == Schema Information
#
# Table name: repartitions
#
#  id                    :bigint           not null, primary key
#  disabled_at           :datetime
#  label                 :text             not null
#  salaire_de_base_cents :integer          default(0), not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#
class Repartition < ApplicationRecord
  has_many :tranches, dependent: :destroy
  has_many :affaires, dependent: :restrict_with_error

  monetize :salaire_de_base_cents, disable_validation: true

  MAX_INT = 2 ** 62

  scope :enabled, -> { where(disabled_at: nil) }

  def enabled
    disabled_at.nil?
  end

  def enabled=(enabled)
    if enabled.to_b
      self.disabled_at = nil
    else
      self.disabled_at ||= DateTime.now
    end
  end

  def compute_contribution(amount)
    # We sort from the highest tranche to the smallest
    tranches = self.tranches.sort { |a, b| b.lower_bound  <=> a.lower_bound }

    result = tranches.inject({contribution: Money.new(0), upper_bound: Money.new(MAX_INT)}) do |result, tranche|
      if amount > tranche.lower_bound
        to_split = [result[:upper_bound], amount].min - tranche.lower_bound
        contribution = result[:contribution] + to_split * tranche.rate

        {contribution: contribution, upper_bound: tranche.lower_bound}
      else
        result
      end
    end

    result[:contribution] - salaire_de_base
  end

  # Given a list of Affaires, compute the total Shared Contribution
  def self.total_contribution(all_affaires)
    # Each Repartition is independent from the others.
    contribution = all_affaires.group_by(&:repartition).sum(0) do |repartition, model_affaires|
      # But all the affaires for this Repartition can be taken together.
      total_affaires = model_affaires.map(&:amount).sum(0)
      # Tranches boundaries are for a whole year;
      # Just take the prorata according to the total number of months with this Repartition
      months_count = model_affaires.map{ |i| i.activite_mensuelle.mois }.uniq.size
      ratio = 12.0 / months_count
      extrapolated_year_affaire = total_affaires * ratio
      extrapolated_year_contribution = repartition.compute_contribution(extrapolated_year_affaire)
      repartition_contribution = extrapolated_year_contribution / ratio
      repartition_contribution
    end

    Money.new(contribution)
  end
end

app/controllers/repartitions_controller.rb
class RepartitionsController < ApplicationController
  before_action :set_repartition, only: [:show, :edit, :update, :destroy]

  # GET /repartitions
  def index
    @repartitions = Repartition.all
  end

  # GET /repartitions/1
  def show
  end

  # GET /repartitions/new
  def new
    @repartition = Repartition.new
  end

  # GET /repartitions/1/edit
  def edit
  end

  # POST /repartitions
  def create
    @repartition = Repartition.new(repartition_params)

    if @repartition.save
      redirect_to @repartition, notice: 'Modèle de répartition créé.'
    else
      render :new
    end
  end

  # PATCH/PUT /repartitions/1
  def update
    if @repartition.update(repartition_params)
      redirect_to @repartition, notice: 'Modèle de répartition mis à jour.'
    else
      render :edit
    end
  end

  # DELETE /repartitions/1
  def destroy
    if @repartition.destroy
      redirect_to repartitions_url, notice: 'Modèle de répartion supprimé.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repartition
      @repartition = Repartition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repartition_params
      params.require(:repartition).permit(:label, :salaire_de_base, :enabled)
    end
end

app/views/repartitions/_form.html.erb
<%= form_with(model: repartition, local: true) do |form| %>
  <% if repartition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repartition.errors.count, "error") %> prohibited this repartition from being saved:</h2>

      <ul>
      <% repartition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :enabled, class: 'checkbox subtitle' do %>
      <%= form.check_box :enabled, class: "checkbox subtitle" %>
      Activé
    <% end %>
  </div>

  <div class="field">
    <%= form.label 'Nom', class: "label" %>
    <div class="control">
        <%= form.text_field :label, id: :repartition_label, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label 'Base', class: "label" %>
    <div class="control">
      <%= form.money_field :salaire_de_base, class: "input" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit :Enregistrer, class: "button is-link"%>
  </div>
<% end %>

app/views/repartitions/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Modification d’un modèle de répartition</h1>

    <%= render 'form', repartition: @repartition %>

    <br/>

    <h2 class="subtitle"> Tranches de contribution</h2>
    <div>
      <table id=tranches class="table">
        <thead>
          <th> À partir de </th>
          <th> mutualiser </th>
        </thead>
        <tbody>
          <%= render @repartition.tranches%>
        </tbody>
      </table>

      <%= form_for @repartition.tranches.new do |f| %>
        <%= f.hidden_field :repartition_id, value: @repartition.id %>
        <div class="field is-grouped">
          <div class="field has-addons">
            <p class="control">
              <a class="button is-static">
                À partir de
              </a>
            </p>
            <p class="control is-expanded">
              <%= f.money_field :lower_bound, class: "input" %>
            </p>
          </div>
          <div class="field has-addons">
            <p class="control">
              <a class="button is-static">
                Mutualiser
              </a>
            </p>
            <p class="control is-expanded">
              <%= f.number_field :rate_percent, in: -100..100, class: "input"%>
            </p>
            <p class="control">
              <a class="button is-static">
                %
              </a>
            </p>
          </div>
            <p class="control">
            <%= f.submit 'Ajouter une tranche', class: "button is-info"%>
            </p>
          </div>
        <% end %>
        </div>

        <%= link_to 'Voir', @repartition, class: "button is-link" %>
        <%= link_to 'Retour', repartitions_path, class: "button is-text" %>
    </div>
</section>

app/views/repartitions/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Modèles de répartition</h1>

    <table class="table is-hover is-bordered">
      <thead>
        <tr>
          <th>Étiquette</th>
          <th>Tranches</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @repartitions.each do |repartition| %>
          <tr>
            <td>
              <b>
                <%= repartition.label %>
              </b>
              <% if !repartition.enabled %>
                <p>
                  <em>
                    <%= "(désactivé le #{l(repartition.disabled_at.to_date)})" %>
                  </em>
                </p>
              <% end %>
              <% if repartition.salaire_de_base.present? %>
                <p>
                  <%= "Base : #{repartition.salaire_de_base.format})" %>
                </p>
              <% end %>
            </td>
            <td><ul>
                <% repartition.tranches.each do |tranche| %>
                  <li><%= tranche.lower_bound.format %> : <%= "%.2f" % (tranche.rate * 100) %> %</li>
                <% end %>
              </ul></td>
              <td><%= link_to 'Voir', repartition %></td>
              <td><%= link_to 'Modifier', edit_repartition_path(repartition) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Nouveau modèle de répartition', new_repartition_path, class: "button is-primary" %>
  </div>
</section>

app/views/repartitions/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Nouveau modèle de contribution</h1>

    <%= render 'form', repartition: @repartition %>
    <br/>

    <%= link_to 'Retour', repartitions_path, class: "button is-text" %>
  </div>
</section>

app/views/repartitions/show.html.erb
<section class="section">
  <div class="container">
    <p>
      <em>
        <% if @repartition.enabled %>
          Actif
        <% else %>
          <%= "Désactivé le #{l(@repartition.disabled_at.to_date)}" %>
        <% end %>
      </em>
    </p>
    <p>
      <strong>Label :</strong>
      <%= @repartition.label %>
    </p>
    <% if @repartition.salaire_de_base.present? %>
      <p>
        <strong>Base :</strong>
        <%= @repartition.salaire_de_base.format %>
      </p>
    <% end %>
    <table class="table">
      <thead>
        <th> À partir de </th>
        <th> mutualiser </th>
      </thead>
      <tbody>
        <%= render @repartition.tranches%>
      </tbody>
    </table>

    <%= link_to 'Éditer', edit_repartition_path(@repartition), class: "button is-link" %>
    <%= link_to 'Retour', repartitions_path, class: "button is-text" %>
  </div>
</section>