config/routes.rb
Rails.application.routes.draw do
  resources :benefices
  resources :tranches
  resources :repartitions
  resources :salaires
  resources :frais

  resources :associates
  resources :affaires

  resources :bilan, only: :index do
    collection do
      get :annuels
      get :mensuels
    end
  end

  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/activites_mensuelles/_activite_mensuelle.html.erb
<div class="block history-month">
  <h4 class="title is-4">
    <%= activite_mensuelle.mois.to_s.capitalize %>
  </h4>
  <div class="columns">
    <div class="column affaires">
      <%= render 'activites_mensuelles/total', label: I18n.t('activerecord.models.affaire/short'), amount: activite_mensuelle.total_affaires %>
      <%= render partial: "affaires/affaire", collection: activite_mensuelle.affaires, cached: true %>
      <%= link_to t("helpers.new"), new_affaire_path(activite_mensuelle_id: activite_mensuelle.id), class: "js-modal-trigger history-editable", data: { target: "app-modal", 'turbo-frame': "modal-content" } %>
    </div>
    <div class="column frais">
      <%= render 'activites_mensuelles/total', label: Frais.model_name.human, amount: activite_mensuelle.total_frais %>
      <%= render partial: "frais/frais", collection: activite_mensuelle.frais, cached: true %>
      <%= link_to t("helpers.new"), new_frais_path(activite_mensuelle_id: activite_mensuelle.id), class: "js-modal-trigger history-editable", data: { target: "app-modal", 'turbo-frame': "modal-content" } %>
    </div>
    <div class="column salaires">
      <%= render 'activites_mensuelles/total', label: Salaire.model_name.human, amount: activite_mensuelle.total_salaires %>
      <% if activite_mensuelle.salaire %>
        <%= render activite_mensuelle.salaire  %>
      <% else %>
        <%= link_to t("helpers.new"), new_salaire_path(activite_mensuelle_id: activite_mensuelle.id), class: "js-modal-trigger history-editable", data: { target: "app-modal", 'turbo-frame': "modal-content" } %>
      <% end %>
    </div>
    <div class="column month_summary">
      <%= render 'activites_mensuelles/total', label: t('summary'), amount: activite_mensuelle.net_balance %>
      <%= render 'activites_mensuelles/summary', summary: activite_mensuelle %>
    </div>
    <div class="column global_summary">
      <%= render 'activites_mensuelles/total', label: t('global_summary'), amount: activite_mensuelle.past_bilan.net_balance %>
      <%= render 'activites_mensuelles/summary', summary: activite_mensuelle.past_bilan %>
    </div>
  </div>
</div>

app/views/activites_mensuelles/_summary.html.erb
<%= render 'value', label: t('attributes.affaires'), amount: summary.total_affaires %>
<%= render 'value', label: t('attributes.contribution'), amount: -summary.total_contribution %>
<%= render 'value', label: t('attributes.frais'), amount: -summary.total_frais %>
<%= render 'value', label: t('attributes.salaire'), amount: -summary.total_salaires %>

app/views/activites_mensuelles/_total.html.erb
<h6 class="subtitle is-6 is-flex is-justify-content-space-between">
  <span>
    <%= label %>
  </span>
  <span>
    <%= (amount || Money.zero).format %>
  </span>
</h6>